version: '3'
services:
  mongo_service:  # MongoDB service
    image: mongo:latest
    container_name: mongo_service
    ports:
      - "27018:27017"  # Use 27018 on host, 27017 inside container
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB

  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - '5002:5000'  # Map host port 5001 to container port 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      MONGO_URI: mongodb://mongo_service:27017/TaskSorting
    depends_on:
      - mongo_service
    command: npm start

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --port 3000"


volumes:
  mongo-data:  # Define the volume for MongoDB



