version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb
    command: npm start

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
